name: candidate-models
channels:
- defaults
- anaconda
- pytorch
dependencies:
  - python>=3.6
  - keras
  - tensorflow>=1.4
  - pytorch
  - torchvision
  - h5py
  - networkx
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - jupyter
  - pytest
  - pytest-mock
  - pip:
    - git+https://github.com/dicarlolab/brain-score
    - git+https://github.com/rcmalli/keras-squeezenet.git
    - pillow
    - llist
    - git+https://github.com/mschrimpf/caching
